TARGET_USER="zeld-a"
DOTFILES_URL="https://github.com/zeld-a/arch-sama-dots.git"

# System Utilities
SYS_UTILS=(
avahi
bluez
bluez-utils
btop
impala
iwd
openrgb
openssh
pacman-contrib
stow
tailscale
unzip
wget
)

# Development Tools
DEV_TOOLS=(
git
intellij-idea-ultimate-edition
)

# Toolchains
TOOLCHAINS=(
jdk21-openjdk
rustup
)

# Desktop Environment
DESKTOP=(
bluetui
fastfetch
hypridle
hyprland
hyprlock
hyprpaper
hyprshot
kitty
nautilus
nwg-look
python-pywal
rofi
starship
swaync
waybar
wlogout
)

# Fonts
FONTS=(
adobe-source-han-sans-jp-fonts
ttf-google-sans
ttf-profont-nerd
)

# Applications
APPS=(
anki
audacity
calibre
chromium
gimp
libreoffice-fresh
nextcloud-client
obs-studio
obsidian
prismlauncher
qbittorrent
steam
vesktop
vlc
)

# Services
SERVICES=(
avahi-daemon
bluetooth
iwd
sshd
tailscaled
)

# User Services
USER_SERVICES=(
)